#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /{_locale}
        permanent: true
        requirements:
            _locale: fr|en
            defaults: { _locale: fr}